# yamllint disable rule:line-length
---
name: tflint

description: |
  Run terraform-linters/tflint in working-directory.

  Overrides available:
  - generates a .tflint.hcl config file to support the tflint-provider specified.
  - You can fully manage configuration by maintaining .tflint.hcl in your repo.
  - if you include a .tflint.hcl file, you must specify a provider.

inputs:

  working-directory:
    description: specific folder in which to run the commands
    required: false
    default: "."

  tflint-provider:
    description: f
    required: false
    default: ""

  tflint-provider-version:
    description: f
    required: false
    default: ""

  tflint-additional-args:
    description: |
      Include any additional tflint commandline arguments. Note: not all
      options can be successfully used in a pipeline.
    required: false
    default: ""

runs:
  using: "composite"

  steps:
    - name: tflint scan of terraform files
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        #!/bin/bash
        install_provider_plugin() {
          cat <<- EOD > .tflint.hcl
          plugin "${{ inputs.tflint-provider }}" {
            enabled = true
            version = "${{ inputs.tflint-provider-version }}"
            source = "github.com/terraform-linters/tflint-ruleset-${{ inputs.tflint-provider }}"
          }
        EOD
        }

        install_provider_plugin
        tflint --version
        tflint --init
        tflint ${{ inputs.tflint-additional-args }}
