# yamllint disable rule:line-length
---
name: trivy scan

description: Run trivy scan in working-director. Default commandline args = config . --exit-code 1

inputs:

  working-directory:
    description: specific folder in which to run the commands
    required: false
    default: "."

  trivy-commandline-args:
    description: Provide additional trivy commandline arguments.
    required: false
    default: "config . --exit-code 1"

runs:
  using: "composite"

  steps:
    - name: trivy scan of terraform files
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        #!/usr/bin/env bash
        set -oe pipefail

        echo "Perform trivy scan"
        trivy --version
        trivy ${{ inputs.trivy-commandline-args }}
