# yamllint disable rule:line-length
---
name: conftest

description: Run conftest in working-directory.

inputs:

  working-directory:
    description: Set working directory. Default is ./.
    required: false
    default: "."

  conftest-version:
    description: |
      Specify conftest version to perform test. Set version "installed" to
      perform scan with the version already installed on the Runner.
    required: false
    default: ""

  terraform-plan-outfile:
    description: Provide name of terraform plan output file for targeted scan.
    required: false
    default: ""

  policy-path:
    description: Path of Conftest policy directory
    required: true
    default: ""

  output-type:
    description: The type of output to use for conftest tes results
    required: false
    default: "table"

  conftest-additional-args:
    description: Set specific commandline arguments. Default is "-d .".
    required: false
    default: ""

runs:
  using: "composite"

  steps:
    - name: conftest test terraform files
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        #!/usr/bin/env bash
        if [[ "${{ inputs.conftest-version }}" != "" ]]; then
          echo "Perform conftest test"
          conftest --version
          echo -e "\n****************\n*   CONFTEST   *\n****************\n" | tee -a conftest_results.txt
          conftest test ./${{ inputs.terraform-plan-outfile }}.tfplan.json -p ${{ inputs.policy-path }}/ --output ${{ inputs.output-type }} ${{ inputs.conftest-additional-args }} | tee -a conftest_results.txt
        fi
    - name: Archive Conftest scan results
      working-directory: ${{ inputs.working-directory }}
      uses: actions/upload-artifact@v4
      with:
        name: conftest-results
        path: conftest_results.txt
