# yamllint disable rule:line-length
# yamllint disable rule:truthy
# yamllint disable rule:comments-indentation
---
name: terraform destroy

on:
  workflow_call:

    secrets:
      OP_SERVICE_ACCOUNT_TOKEN:
        description: 1password vault services account token
        required: false

    inputs:

      working-directory:
        description: Set working directory. Default is ./.
        required: false
        type: string
        default: .

      terraform-version:
        description: Specify terraform version or "installed" to perform scan. Leave blank to skip.
        required: false
        type: string
        default: "false"

      workspace:
        description: terraform environment workspace
        required: true
        type: string

      terraform-destroy-additional-args:
        description: |
          Include any additional terraform apply command arguments. Can be used in conjunction with
          terraform-var-file parameter or an override.
        required: false
        type: string
        default: ""

      terraform-var-file:
        description: Include terraform -var-file parameter.
        required: false
        type: string
        default: ""

      before-init:
        description: optionally call ./.github/actions/before-init before performing terraform init
        required: false
        type: string
        default: "false"

      after-init:
        description: optionally call ./.github/actions/after-init after performing terraform init
        required: false
        type: string
        default: "false"

      after-destroy:
        description: optionally call ./.github/actions/after-destroy after performing terraform destroy
        required: false
        type: string
        default: "false"

      job-container-image:
        description: default is latest
        type: string
        required: false
        default: "twdps/gha-container-infra-aws:latest"
jobs:

  terraform-destroy:
    name: terraform apply
    runs-on: ubuntu-latest
    container: ${{ inputs.job-container-image }}

    env:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      TF_WORKSPACE: ${{ inputs.workspace }}

    steps:
      - name: checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29      # v4.1.6

      - name: install terraform workflow packages
        uses: ThoughtWorks-DPS/terraform-action/install@main
        with:
          working-directory: ${{ inputs.working-directory }}
          terraform-version: ${{ inputs.terraform-version }}

      - name: run custom before-init action
        if: ${{ inputs.before-init != 'false' }}
        uses: ./.github/actions/before-init
        with:
          instance: ${{ inputs.before-init }}

      - name: terraform init
        working-directory: ${{ inputs.working-directory }}
        shell: bash
        run: |
          terraform version
          terraform init ${{ inputs.terraform-init-additional-args }}

      - name: run custom after-init action
        if: ${{ inputs.after-init != 'false' }}
        uses: ./.github/actions/after-init
        with:
          instance: ${{ inputs.after-init }}

      - name: run terraform destroy in working directory
        uses: ThoughtWorks-DPS/terraform-action/destroy@main
        with:
          working-directory: ${{ inputs.working-directory }}
          terraform-destroy-additional-args: ${{ inputs.terraform-apply-additional-args }}
          terraform-var-file: ${{ inputs.terraform-var-file }}

      - name: run custom after-destroy action
        if: ${{ inputs.after-destroy != 'false' }}
        uses: ./.github/actions/after-destroy
        with:
          instance: ${{ inputs.after-destroy }}
