# yamllint disable rule:line-length
# yamllint disable rule:truthy
---
run-name: terraform static code analysis

on:
  workflow_call:

    inputs:

      working-directory:
        description: Set working directory. Default is ./.
        required: false
        type: string
        default: .

jobs:

  terraform-static-code-analysis:
    name: terraform static code analysis
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.1
