# yamllint disable rule:line-length
# yamllint disable rule:truthy
---
run-name: static code analysis

on:
  workflow_call:

    inputs:

      working-directory:
        description: Set working directory. Default is ./.
        required: false
        type: string
        default: .

jobs:

  static-code-analysis:
    name: static code analysis
    runs-on: ubuntu-latest
    container: twdps/gha-container-base-image:alpine-stable

    steps:
      - name: checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b          # v4.1.4

      - name: check context
        shell: bash
        run: |
          apk list
          op --help
