# yamllint disable rule:line-length
# yamllint disable rule:truthy
---
name: static code analysis

on:
  workflow_call:

    secrets:
      OP_SERVICE_ACCOUNT_TOKEN:
        description: 1password vault services account token
        required: false

    inputs:

      working-directory:
        description: Set working directory. Default is ./.
        required: false
        type: string
        default: .

      job-container-image:
        description: default is latest
        type: string
        required: false
        default: "twdps/gha-container-infra-aws:latest"

jobs:

  static-code-analysis:
    name: static code analysis
    runs-on: ubuntu-latest
    container: ${{ inputs.job-container-image }}

    env:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

    steps:
      - name: checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29      # v4.1.6

      - name: check context
        shell: bash
        run: |
          apk list
          op --help
