# yamllint disable rule:line-length
# yamllint disable rule:truthy
# yamllint disable rule:comments-indentation
---
name: terraform plan

on:
  workflow_call:

    secrets:
      OP_SERVICE_ACCOUNT_TOKEN:
        description: 1password vault services account token
        required: false

    inputs:

      working-directory:
        description: Set working directory. Default is ./.
        required: false
        type: string
        default: .

      terraform-version:
        description: Specify terraform version or "installed" to perform scan. Leave blank to skip.
        required: false
        type: string
        default: "false"

      workspace:
        description: terraform environment workspace
        required: true
        type: string

      tfc-workspace:
        description: Create and/or set local-mode workspace.
        required: false
        type: string
        default: ""

      tfc-organization:
        description: Terraform cloud organization name.
        required: false
        type: string
        default: ""

      checkov-version:
        description: Specify checkov version or "installed" to perform scan. Leave blank to skip.
        required: false
        type: string
        default: "false"

      checkov-scan:
        description: perform checkov scan of terraform files
        required: false
        type: string
        default: "false"

      checkov-additional-args:
        description: Set specific commandline arguments. Default is "-d .".
        required: false
        type: string
        default: "-d ."

      terraform-plan-outfile:
        description: Provide name of terraform plan output file for targeted scan.
        required: false
        type: string
        default: "tfplan.json"

      terraform-plan-additional-args:
        description: |
          Include any additional terraform plan command arguments. Can be used in conjunction with
          terraform-var-file parameter or an override.
        required: false
        type: string
        default: ""

      terraform-var-file:
        description: Include terraform -var-file parameter.
        required: false
        type: string
        default: ""

      before-init:
        description: optionally call ./.github/actions/before-init before performing terraform init
        required: false
        type: string
        default: "false"

      after-init:
        description: optionally call ./.github/actions/after-init after performing terraform init
        required: false
        type: string
        default: "false"

      after-plan:
        description: optionally call ./.github/actions/after-plan after performing terraform plan
        required: false
        type: string
        default: "false"
        
      job-container-image:
        description: default is latest
        type: string
        required: false
        default: "twdps/gha-container-infra-aws:latest"
jobs:

  terraform-plan:
    name: terraform
    runs-on: ubuntu-latest
    container: ${{ inputs.job-container-image }}

    env:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      TF_WORKSPACE: ${{ inputs.workspace }}

    steps:
      - name: checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29      # v4.1.6

      - name: install terraform workflow packages
        uses: ThoughtWorks-DPS/terraform-action/install@main
        with:
          working-directory: ${{ inputs.working-directory }}
          terraform-version: ${{ inputs.terraform-version }}
          checkov-version: ${{ inputs.checkov-version }}

      - name: run custom before-init action
        if: ${{ inputs.before-init != 'false' }}
        uses: ./.github/actions/before-init
        with:
          instance: ${{ inputs.before-init }}

      - name: Confirm or Create tfcloud workspace in local-execute-mode
        if: ${{ inputs.tfc-workspace != '' }}
        uses: ThoughtWorks-DPS/terraform-action/use-tfc-local-mode@main
        with:
          working-directory: ${{ inputs.working-directory }}
          tfc-workspace: ${{ inputs.tfc-workspace }}
          tfc-organization: ${{ inputs.tfc-organization }}

      - name: terraform init
        working-directory: ${{ inputs.working-directory }}
        shell: bash
        run: |
          terraform version
          terraform init ${{ inputs.terraform-init-additional-args }}

      - name: run custom after-init action
        if: ${{ inputs.after-init != 'false' }}
        uses: ./.github/actions/after-init
        with:
          instance: ${{ inputs.after-init }}

      - name: run terraform plan in working directory
        uses: ThoughtWorks-DPS/terraform-action/plan@main
        with:
          working-directory: ${{ inputs.working-directory }}
          terraform-plan-outfile: ${{ inputs.terraform-plan-outfile }}
          terraform-plan-additional-args: ${{ inputs.terraform-plan-additional-args }}
          terraform-var-file: ${{ inputs.terraform-var-file }}

      - name: perform checkov scan of terraform source files
        if: ${{ inputs.checkov-scan == 'true' }}
        uses: ThoughtWorks-DPS/terraform-action/checkov-scan@main
        with:
          working-directory: ${{ inputs.working-directory }}
          terraform-plan-outfile: ${{ inputs.terraform-plan-outfile }}
          checkov-additional-args: ${{ inputs.checkov-additional-args }}

      - name: run custom after-plan action
        if: ${{ inputs.after-plan != 'false' }}
        uses: ./.github/actions/after-plan
        with:
          instance: ${{ inputs.after-plan }}
