# yamllint disable rule:line-length
---
run-name: static code analysis

on:
  workflow_call:

jobs:

  static-code-analysis:
    name: static code analysis
    runs-on: ubuntu-latest
    container: twdps/circleci-infra-aws:alpine-stable

    steps:
      - name: checkout code
        uses: actions/checkout@actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b          # v4.1.4

      - name: check container context
        shell: ash
        run: apk list