---
run-name: Terraform static code analysis

on:
  workflow_call:

    inputs:

      working-directory:
        description: set working directory; default is .
        required: false
        type: string
        default: .

      cosign-version:
        description: Specify cosign version
        required: false
        type: string
        default: installed

      terraform-version:
        description: |
          If you specify a specific version, it will be installed and used by
          all orb terraform functions. Leave blank or specify version "installed"
          to use the version already installed on the executor.
        required: false
        type: string
        default: ""

      terraform-init-additional-args:
        description: |
          Include any additional terraform init command arguments.
          Default is -backend=false.
        required: false
        type: string
        default: -backend=false

      tflint-version:
        description: |
          Providing a tflint version results in a tflint scan of the repo using
          the desired version. Specify version "installed" to use the version
          already installed on the executor.
        required: false
        type: string
        default: ""

      tflint-provider:
        description: provider for tflint plugin
        required: false
        type: string
        default: aws

      tflint-additional-args:
        description: |
          Include any additional tflint commandline arguments. Note: not all
          options can be successfully used in a pipeline.
        required: false
        type: string
        default: ""
    
      before-static-analysis:
        description: Optional steps to run before running static analysis
        required: false
        type: string
        default: echo "none"

      after-static-analysis:
        description: Optional steps to run before after static analysis
        required: false
        type: string
        default: echo "none"

jobs:

  terraform-static-code-analysis:
    name: terraform static code analysis
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.1

      - name: install terraform workflow packages
        uses:  ThoughtWorks-DPS/terraform-action/packages@main
        with:
          working-directory: ${{ inputs.working-directory }}
          terraform-version: ${{ inputs.terraform-version }}
          tflint-version: ${{ inputs.tflint-version }}

      - name: run custom before-analysis scripts
        working-directory: ${{ inputs.working-directory }}
        shell: bash
        run: ${{ inputs.before-static-analysis }}

      - name: terraform init
        working-directory: ${{ inputs.working-directory }}
        shell: bash
        run: |
          terraform version
          terraform init ${{ inputs.terraform-init-additional-args }}

      - name: evaluate canonical format of terraform files 
        working-directory: ${{ inputs.working-directory }}
        shell: bash
        run: terraform fmt -check=false

      - name: validate terraform syntax
        working-directory: ${{ inputs.working-directory }}
        shell: bash
        run: terraform validate

      - if: ${{ inputs.tflint-version }} != ""
        name: perform tflint scan of terraform source files
        uses:  ThoughtWorks-DPS/terraform-action/tflint@main
        with:
          working-directory: ${{ inputs.working-directory }}
          tflint-provider: ${{ inputs.tflint-provider }}
          tflint-additional-args: ${{ inputs.tflint-additional-args }}


# tflint
# tfsec (none plan output)
# checkov (none plan output)
# snyk iac
# terrascan
# driftctl
# infracost

      - name: run custom after-analysis scripts
        working-directory: ${{ inputs.working-directory }}
        shell: bash
        run: ${{ inputs.after-static-analysis }}




      # echo "action_state=yellow" >> "$GITHUB_ENV"