run-name: Terraform static code analysis

on:
  workflow_call:

    inputs:

      working-directory:
        description: set working directory; default is .
        required: false
        type: string
        default: .

      terraform-version:
        description: |
          If you specify a specific version, it will be installed and used by
          all orb terraform functions. Leave blank or specify version "installed"
          to use the version already installed on the executor.
        required: false
        type: string
        default: ""

      before-static-analysis:
        description: Optional steps to run before running static analysis
        required: false
        type: string
        default: ""

jobs:

  static-code-analysis:
    name: static code analysis
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.1

      - name: install packages
        uses:  ThoughtWorks-DPS/terraform-action/packages@main
        with:
          working-directory: ${{ inputs.working-directory }}
          terraform-version: ${{ inputs.terraform-version }}

      - name: run custom before-analysis scripts
        if: ${{ inputs.working-directory }} != "."
        working-directory: ${{ inputs.working-directory }}
        shell: bash
        run: ${{ inputs.before-static-analysis }}


      # - name: configure shared pipeline job environment
      #   uses: ./.github/actions/setup-pipeline-env
      #   with:
      #     secrethub-creds: ${{ secrets.SECRETHUB_CREDENTIAL }}
      #     tfvar-env: gha-sandbox
      # echo "action_state=yellow" >> "$GITHUB_ENV"